version: '3'
services:
  backend:
    image: annaplaideau/labdockerannaplaideau:latest
    ports:
      - 8080:5000
    environment:
      - CURRENT_ENVIRONMENT=production
    volumes:
      - data:/app/data

   frontend:
    image: annaplaideau/frontimage:latest
    ports:
      - 8081:80
    environment:
      - WS_BACK_URL=http://localhost:8080

volumes:
  data:
    name: data-volume